### ISSUE TITLE
Feature animate.css

### ISSUE THREAD

**Issue by buepro** [Twikito/onscroll-effect#19]
It would be interesting to use this library together with [animate.css](https://github.com/animate-css/animate.css). For this it would be needed to enable adding several classes to the data attribute (e.g. `data-scroll="animate__animated animate__bounce"`).

**Comment by Twikito** [comment]
Thanks @buepro for taking time adding this request!

Actually, you're right! I'll do that.

**Comment by Twikito** [comment]
Hey @buepro 👋 

The job is done: you can now add as many classes as you want!

**Comment by buepro** [comment]
Hi @Twikito, thank you very much for this! I just integrated it into the [TYPO3 extension pizpalue](https://docs.typo3.org/p/buepro/typo3-pizpalue/master/en-us/User/Animation.html#twikito-onscroll-effect).
